if (typeof window !== "undefined") {
  const registeredUsers = localStorage.getItem("registeredUsers");
  if (!registeredUsers) {
    localStorage.setItem(
      "registeredUsers",
      JSON.stringify([
        {
          email: "test@example.com",
          password: "password123",
          userId: "user-1",
        },
      ])
    );
  }
}

export const currentUser = {
  id: "user-1",
  username: "김민수",
  displayName: "민수",
  gender: "male",
  major: "컴퓨터공학과",
  year: 3,
  age: 22,
  instagramId: "minsu_kim",
  phoneNumber: "010-1234-5678",
  kakaoId: "minsu22",
  bio: "안녕하세요! 게임과 음악을 좋아합니다 🎮🎵",
  privacySettings: {
    showName: true,
    showMajor: true,
    showYear: true,
    showAge: false,
  },
  createdAt: new Date("2024-09-01"),
};

export const dummyUsers = [
  currentUser,
  {
    id: "user-2",
    username: "이지은",
    displayName: "지은",
    gender: "female",
    major: "경영학과",
    year: 2,
    age: 21,
    instagramId: "jieun_lee",
    kakaoId: "jieun21",
    bio: "카페 투어 좋아해요 ☕️",
    privacySettings: {
      showName: true,
      showMajor: true,
      showYear: true,
      showAge: true,
    },
    createdAt: new Date("2024-09-05"),
  },
  {
    id: "user-3",
    username: "박준호",
    displayName: "준호",
    gender: "male",
    major: "신학과",
    year: 4,
    age: 24,
    phoneNumber: "010-3456-7890",
    kakaoId: "junho_park",
    bio: "운동과 독서를 즐깁니다 📚",
    privacySettings: {
      showName: true,
      showMajor: true,
      showYear: false,
      showAge: false,
    },
    createdAt: new Date("2024-08-20"),
  },
  {
    id: "user-4",
    username: "최서연",
    displayName: "서연",
    gender: "female",
    major: "간호학과",
    year: 3,
    age: 22,
    instagramId: "seoyeon_choi",
    phoneNumber: "010-5678-9012",
    bio: "여행 가고 싶어요 ✈️",
    privacySettings: {
      showName: true,
      showMajor: true,
      showYear: true,
      showAge: true,
    },
    createdAt: new Date("2024-09-10"),
  },
  {
    id: "user-5",
    username: "정우진",
    displayName: "우진",
    gender: "male",
    major: "물리치료학과",
    year: 2,
    age: 20,
    instagramId: "woojin_j",
    kakaoId: "woojin20",
    bio: "영화 보는 걸 좋아합니다 🎬",
    privacySettings: {
      showName: true,
      showMajor: true,
      showYear: true,
      showAge: false,
    },
    createdAt: new Date("2024-09-15"),
  },
];

export const dummyPosts = [
  {
    id: "post-1",
    authorId: "user-2",
    author: dummyUsers[1],
    content: "오늘 날씨 너무 좋다! 같이 산책할 사람? 🌸",
    color: "pink",
    likes: 12,
    likedBy: ["user-1", "user-3"],
    comments: [
      {
        id: "comment-1",
        postId: "post-1",
        authorId: "user-3",
        author: dummyUsers[2],
        content: "저요! 몇 시에 어디서 만날까요?",
        createdAt: new Date("2025-10-29T10:30:00"),
      },
    ],
    createdAt: new Date("2025-10-29T09:15:00"),
  },
  {
    id: "post-2",
    authorId: "user-3",
    author: dummyUsers[2],
    content: "이번 주말에 영화 보러 갈 사람 구해요~ 액션 영화 좋아하시는 분!",
    color: "yellow",
    likes: 8,
    likedBy: ["user-5"],
    comments: [],
    createdAt: new Date("2025-10-29T08:45:00"),
  },
  {
    id: "post-3",
    authorId: "user-4",
    author: dummyUsers[3],
    content: "학교 근처 맛집 추천해주세요! 특히 파스타 맛있는 곳 🍝",
    color: "pink",
    likes: 15,
    likedBy: ["user-1", "user-2", "user-5"],
    comments: [
      {
        id: "comment-2",
        postId: "post-3",
        authorId: "user-2",
        author: dummyUsers[1],
        content: "정문 앞에 이탈리안 레스토랑 진짜 맛있어요!",
        createdAt: new Date("2025-10-29T11:00:00"),
      },
    ],
    createdAt: new Date("2025-10-29T11:20:00"),
  },
  {
    id: "post-4",
    authorId: "user-5",
    author: dummyUsers[4],
    content: "같이 공부할 스터디 메이트 찾아요 📚 중간고사 준비하실 분!",
    color: "yellow",
    likes: 6,
    likedBy: ["user-1"],
    comments: [],
    createdAt: new Date("2025-10-29T07:30:00"),
  },
  {
    id: "post-5",
    authorId: "user-1",
    author: dummyUsers[0],
    content: "오늘 점심 같이 먹을 사람? 학식 ㄱㄱ",
    color: "pink",
    likes: 10,
    likedBy: ["user-2", "user-4"],
    comments: [
      {
        id: "comment-3",
        postId: "post-5",
        authorId: "user-4",
        author: dummyUsers[3],
        content: "저요! 12시에 학생식당에서 만나요~",
        createdAt: new Date("2025-10-29T11:45:00"),
      },
    ],
    createdAt: new Date("2025-10-29T11:30:00"),
  },
];

export const dummyNotifications = [
  {
    id: "notif-1",
    userId: "user-1",
    type: "like",
    fromUser: dummyUsers[1],
    postId: "post-5",
    message: "이지은님이 회원님의 게시물을 좋아합니다",
    read: false,
    createdAt: new Date("2025-10-29T11:35:00"),
  },
  {
    id: "notif-2",
    userId: "user-1",
    type: "comment",
    fromUser: dummyUsers[3],
    postId: "post-5",
    message: "최서연님이 회원님의 게시물에 댓글을 남겼습니다",
    read: false,
    createdAt: new Date("2025-10-29T11:45:00"),
  },
  {
    id: "notif-3",
    userId: "user-1",
    type: "like",
    fromUser: dummyUsers[2],
    postId: "post-5",
    message: "박준호님이 회원님의 게시물을 좋아합니다",
    read: false,
    createdAt: new Date("2025-10-29T10:20:00"),
  },
];
